import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import RootNavigation from "@/components/root-navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-backgroundGradientStart to-backgroundGradientEnd`}
      >
        <RootNavigation />
        <main>{children}</main>
      </body>
    </html>
  );
}
